# Generated by Django 3.2.8 on 2021-11-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='telephone',
        ),
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.CharField(max_length=255, null=True, verbose_name='about'),
        ),
    ]
