# Generated by Django 3.2.8 on 2021-11-22 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_auto_20211121_2338'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('photo', models.ImageField(null=True, upload_to='photos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to=settings.AUTH_USER_MODEL, verbose_name='user photo')),
            ],
            options={
                'abstract': False,
            },
        )
    ]
