# Generated by Django 3.2.8 on 2021-11-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0004_alter_user_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='current_photo',
        ),
    ]
