# Generated by Django 3.2.8 on 2021-12-01 23:11

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haircut',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True, verbose_name='code'),
        ),
        migrations.CreateModel(
            name='HairCutImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('image', models.ImageField(null=True, upload_to=apps.core.models.haircut_images_path, verbose_name='image')),
                ('default', models.BooleanField(default=False)),
                ('haircut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.haircut', verbose_name='haircut')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
